apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  maxUnavailable: {{ .Values.spec.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}